### ISSUE TITLE
Hi - Is it possible / legal to use Sol in another app?

### ISSUE THREAD

**Issue by daviddelmonte** [Sol-App/Sol#27]
If it's possible and legal, could you please give me a few tips how to accomplish this. I agree with everyone else here - it is beautiful.. Thank you!

**Comment by comyarzaheri** [comment]
Hmmm legal...sure, it's under the MIT license. I'd *prefer* if there were some significant changes made to it if you released an app based on the code, but that's just my preference; legally you can do whatever you like. Thanks for asking beforehand though.

**Comment by daviddelmonte** [comment]
Great. I will change the look so it matches my app. 

What do I do to implement? The main project, the subproject? I can figure out eventually but I’ll be stomping all over your code.

Any implementation info would be very helpful.

On Apr 6, 2015, at 10:46 PM, Comyar Zaheri <notifications@github.com> wrote:

Hmmm legal...sure, it's under the MIT license. I'd prefer if there were some significant changes made to it if you released an app based on the code, but that's just my preference; legally you can do whatever you like. Thanks for asking beforehand though.

**Comment by comyarzaheri** [comment]
Well if you're trying to change the look, I'd start by looking through the views then moving on to the view controllers where you'll find all the interactions/effects.

**Comment by daviddelmonte** [comment]
Ok. Thank you again

Sent from my iPad

On Apr 6, 2015, at 11:22 PM, Comyar Zaheri <notifications@github.com> wrote:

Well if you're trying to change the look, I'd start by looking through the views then moving on to the view controllers where you'll find all the interactions/effects.
